AZURE_OPENAI_API_KEY: null
AZURE_OPENAI_API_VERSION: "2023-05-15"
AZURE_OPENAI_DEPLOYMENT_NAME: gpt-4o
AZURE_OPENAI_ENDPOINT: null
TAVILY_API_KEY: null
LANGCHAIN_API_KEY: null
LANGCHAIN_TRACING_V2: true
LANGCHAIN_ENDPOINT: https://api.smith.langchain.com
LANGCHAIN_HUB_API_URL: https://api.hub.langchain.com
LANGCHAIN_WANDB_TRACING: true
WANDB_PROJECT: 12345
